### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by zweigraf** [staxmanade/diffXcodeTargets#1]
I have an Xcode project with 14 targets. If I call diffXcodeTargets with just the project file, it crashes with above error message:

```
$ diffXcodeTargets xxxxxx.xcodeproj/project.pbxproj
For larger projects, this could take a moment...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[1]    59336 abort      diffXcodeTargets xxxxxx.xcodeproj/project.pbxproj
```

Addition: It even shows the same message when I specify two targets (that should exist in the project).

Just to record this here, I don't expect you to fix this. Maybe I'll have a look myself.

BTW: Thanks for this module, it really helped me already :+1:

**Comment by staxmanade** [comment]
:+1: glad it helped when it did. 

Can you try loading the project up manually using this library? https://github.com/alunny/node-xcode?

This is what this project leverages to load an xcode project...

**Comment by staxmanade** [comment]
Closing for age
