### ISSUE TITLE
mac os 10.11.1 and xcode7.1

### ISSUE THREAD

**Issue by veryitman** [staxmanade/diffXcodeTargets#2]
For larger projects, this could take a moment...

/usr/local/lib/node_modules/diffxcodetargets/node_modules/xcode/lib/parser/pbxproj.js:2654
        throw new this.SyntaxError(
        ^
SyntaxError: Expected "/*", "//" or "{" but "<" found.

**Comment by staxmanade** [comment]
Going to close this for now - if it's still a problem and can be reproduced - feel free to open.
